# Generated by Django 5.1.4 on 2025-03-21 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='clg',
        ),
        migrations.RemoveField(
            model_name='user',
            name='stream',
        ),
    ]
